/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'java' at '16. 7. 19 오후 4:57' with Gradle 2.14
 *
 * @author java, @date 16. 7. 19 오후 4:57
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
